CREATE DATABASE calldata;
USE calldata;

DROP TABLE IF EXISTS `billing`;
CREATE TABLE `billing` (
  `dateTimeConnect` varchar(30) DEFAULT '',
  `CallingPartyNumber` varchar(30) DEFAULT '',
  `dateTimeDisconnect` varchar(50) DEFAULT '',
  `originalCalledPartyNumberPartition` varchar(30) DEFAULT '',
  `origDeviceName` varchar(50) DEFAULT '',
  `destDeviceName` varchar(50) DEFAULT '',
  `originalCalledPartyNumber` varchar(50) DEFAULT '',
  `duration` varchar(50) DEFAULT '',
  `pkid` varchar(100) NOT NULL,
  `dest` varchar(50) DEFAULT '',
  `cost` varchar(11) DEFAULT '',
  PRIMARY KEY (`pkid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `calldetails`;
CREATE TABLE `calldetails` (
  `cdrRecordType` int(11) DEFAULT NULL,
  `globalCallID_callManagerId` int(11) DEFAULT NULL,
  `globalCallID_callId` int(11) DEFAULT NULL,
  `origLegCallIdentifier` int(11) DEFAULT NULL,
  `dateTimeOrigination` int(11) DEFAULT NULL,
  `origNodeId` int(11) DEFAULT NULL,
  `origSpan` int(11) DEFAULT NULL,
  `origIpAddr` int(11) DEFAULT NULL,
  `callingPartyNumber` varchar(50) DEFAULT NULL,
  `callingPartyUnicodeLoginUserID` varchar(128) DEFAULT NULL,
  `origCause_location` int(11) DEFAULT NULL,
  `origCause_value` int(11) DEFAULT NULL,
  `origPrecedenceLevel` int(11) DEFAULT NULL,
  `origMediaTransportAddress_IP` int(11) DEFAULT NULL,
  `origMediaTransportAddress_Port` int(11) DEFAULT NULL,
  `origMediaCap_payloadCapability` int(11) DEFAULT NULL,
  `origMediaCap_maxFramesPerPacket` int(11) DEFAULT NULL,
  `origMediaCap_g723BitRate` int(11) DEFAULT NULL,
  `origVideoCap_Codec` int(11) DEFAULT NULL,
  `origVideoCap_Bandwidth` int(11) DEFAULT NULL,
  `origVideoCap_Resolution` int(11) DEFAULT NULL,
  `origVideoTransportAddress_IP` int(11) DEFAULT NULL,
  `origVideoTransportAddress_Port` int(11) DEFAULT NULL,
  `origRSVPAudioStat` varchar(64) DEFAULT NULL,
  `origRSVPVideoStat` varchar(64) DEFAULT NULL,
  `destLegIdentifier` int(11) DEFAULT NULL,
  `destNodeId` int(11) DEFAULT NULL,
  `destSpan` int(11) DEFAULT NULL,
  `destIpAddr` int(11) DEFAULT NULL,
  `originalCalledPartyNumber` varchar(50) DEFAULT NULL,
  `finalCalledPartyNumber` varchar(50) DEFAULT NULL,
  `finalCalledPartyUnicodeLoginUserID` varchar(128) DEFAULT NULL,
  `destCause_location` int(11) DEFAULT NULL,
  `destCause_value` int(11) DEFAULT NULL,
  `destPrecedenceLevel` int(11) DEFAULT NULL,
  `destMediaTransportAddress_IP` int(11) DEFAULT NULL,
  `destMediaTransportAddress_Port` int(11) DEFAULT NULL,
  `destMediaCap_payloadCapability` int(11) DEFAULT NULL,
  `destMediaCap_maxFramesPerPacket` int(11) DEFAULT NULL,
  `destMediaCap_g723BitRate` int(11) DEFAULT NULL,
  `destVideoCap_Codec` int(11) DEFAULT NULL,
  `destVideoCap_Bandwidth` int(11) DEFAULT NULL,
  `destVideoCap_Resolution` int(11) DEFAULT NULL,
  `destVideoTransportAddress_IP` int(11) DEFAULT NULL,
  `destVideoTransportAddress_Port` int(11) DEFAULT NULL,
  `destRSVPAudioStat` varchar(64) DEFAULT NULL,
  `destRSVPVideoStat` varchar(64) DEFAULT NULL,
  `dateTimeConnect` int(11) DEFAULT NULL,
  `dateTimeDisconnect` int(11) DEFAULT NULL,
  `lastRedirectDn` varchar(50) DEFAULT NULL,
  `pkid` varchar(50) NOT NULL,
  `originalCalledPartyNumberPartition` varchar(50) DEFAULT NULL,
  `callingPartyNumberPartition` varchar(50) DEFAULT NULL,
  `finalCalledPartyNumberPartition` varchar(50) DEFAULT NULL,
  `lastRedirectDnPartition` varchar(50) DEFAULT NULL,
  `duration` int(11) DEFAULT NULL,
  `origDeviceName` varchar(129) DEFAULT NULL,
  `destDeviceName` varchar(129) DEFAULT NULL,
  `origCallTerminationOnBehalfOf` int(11) DEFAULT NULL,
  `destCallTerminationOnBehalfOf` int(11) DEFAULT NULL,
  `origCalledPartyRedirectOnBehalfOf` int(11) DEFAULT NULL,
  `lastRedirectRedirectOnBehalfOf` int(11) DEFAULT NULL,
  `origCalledPartyRedirectReason` int(11) DEFAULT NULL,
  `lastRedirectRedirectReason` int(11) DEFAULT NULL,
  `destConversationId` int(11) DEFAULT NULL,
  `globalCallId_ClusterID` varchar(50) DEFAULT NULL,
  `joinOnBehalfOf` int(11) DEFAULT NULL,
  `comment` varchar(2048) DEFAULT NULL,
  `authCodeDescription` varchar(50) DEFAULT NULL,
  `authorizationLevel` int(11) DEFAULT NULL,
  `clientMatterCode` varchar(32) DEFAULT NULL,
  `origDTMFMethod` int(11) DEFAULT NULL,
  `destDTMFMethod` int(11) DEFAULT NULL,
  `callSecuredStatus` int(11) DEFAULT NULL,
  `origConversationId` int(11) DEFAULT NULL,
  `origMediaCap_Bandwidth` int(11) DEFAULT NULL,
  `destMediaCap_Bandwidth` int(11) DEFAULT NULL,
  `authorizationCodeValue` varchar(32) DEFAULT NULL,
  `outpulsedCallingPartyNumber` varchar(50) DEFAULT NULL,
  `outpulsedCalledPartyNumber` varchar(50) DEFAULT NULL,
  `origIpv4v6Addr` varchar(64) DEFAULT NULL,
  `destIpv4v6Addr` varchar(64) DEFAULT NULL,
  `origVideoCap_Codec_Channel2` int(11) DEFAULT NULL,
  `origVideoCap_Bandwidth_Channel2` int(11) DEFAULT NULL,
  `origVideoCap_Resolution_Channel2` int(11) DEFAULT NULL,
  `origVideoTransportAddress_IP_Channel2` int(11) DEFAULT NULL,
  `origVideoTransportAddress_Port_Channel2` int(11) DEFAULT NULL,
  `origVideoChannel_Role_Channel2` int(11) DEFAULT NULL,
  `destVideoCap_Codec_Channel2` int(11) DEFAULT NULL,
  `destVideoCap_Bandwidth_Channel2` int(11) DEFAULT NULL,
  `destVideoCap_Resolution_Channel2` int(11) DEFAULT NULL,
  `destVideoTransportAddress_IP_Channel2` int(11) DEFAULT NULL,
  `destVideoTransportAddress_Port_Channel2` int(11) DEFAULT NULL,
  `destVideoChannel_Role_Channel2` int(11) DEFAULT NULL,
  `IncomingProtocolID` int(11) DEFAULT NULL,
  `IncomingProtocolCallRef` varchar(32) DEFAULT NULL,
  `OutgoingProtocolID` int(11) DEFAULT NULL,
  `OutgoingProtocolCallRef` varchar(32) DEFAULT NULL,
  `currentRoutingReason` int(11) DEFAULT NULL,
  `origRoutingReason` int(11) DEFAULT NULL,
  `lastRedirectingRoutingReason` int(11) DEFAULT NULL,
  `huntPilotPartition` varchar(50) DEFAULT NULL,
  `huntPilotDN` varchar(50) DEFAULT NULL,
  `calledPartyPatternUsage` int(11) DEFAULT NULL,
  `IncomingICID` varchar(50) DEFAULT NULL,
  `IncomingOrigIOI` varchar(50) DEFAULT NULL,
  `IncomingTermIOI` varchar(50) DEFAULT NULL,
  `OutgoingICID` varchar(50) DEFAULT NULL,
  `OutgoingOrigIOI` varchar(50) DEFAULT NULL,
  `OutgoingTermIOI` varchar(50) DEFAULT NULL,
  `outpulsedOriginalCalledPartyNumber` varchar(50) DEFAULT NULL,
  `outpulsedLastRedirectingNumber` varchar(50) DEFAULT NULL,
  `wasCallQueued` int(11) DEFAULT NULL,
  `totalWaitTimeInQueue` int(11) DEFAULT NULL,
  `callingPartyNumber_uri` varchar(255) DEFAULT NULL,
  `originalCalledPartyNumber_uri` varchar(255) DEFAULT NULL,
  `finalCalledPartyNumber_uri` varchar(255) DEFAULT NULL,
  `lastRedirectDn_uri` varchar(255) DEFAULT NULL,
  `mobileCallingPartyNumber` varchar(50) DEFAULT NULL,
  `finalMobileCalledPartyNumber` varchar(50) DEFAULT NULL,
  `origMobileDeviceName` varchar(129) DEFAULT NULL,
  `destMobileDeviceName` varchar(129) DEFAULT NULL,
  `origMobileCallDuration` int(11) DEFAULT NULL,
  `destMobileCallDuration` int(11) DEFAULT NULL,
  `mobileCallType` int(11) DEFAULT NULL,
  `originalCalledPartyPattern` varchar(50) DEFAULT NULL,
  `finalCalledPartyPattern` varchar(50) DEFAULT NULL,
  `lastRedirectingPartyPattern` varchar(50) DEFAULT NULL,
  `huntPilotPattern` varchar(50) DEFAULT NULL,
  `origDeviceType` varchar(100) DEFAULT NULL,
  `destDeviceType` varchar(100) DEFAULT NULL,
  `origDeviceSessionID` varchar(128) DEFAULT NULL,
  `destDeviceSessionID` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`pkid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `enduser`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `enduser` (
  `userid` int(11) NOT NULL,
  `lastname` varchar(50) DEFAULT NULL,
  `firstname` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `routes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `routes` (
  `pattern` varchar(40) NOT NULL DEFAULT '',
  `comment` varchar(80) DEFAULT NULL,
  `trunks` varchar(180) DEFAULT NULL,
  `connectcost` int(11) NOT NULL DEFAULT 0,
  `includedseconds` int(11) NOT NULL DEFAULT 0,
  `purchase` int(20) DEFAULT NULL,
  `sale` int(20) DEFAULT NULL,
  PRIMARY KEY (`pattern`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
